name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Build project
      run: npm run build

    - name: Print GitHub Context
      run: |
        echo "GITHUB_CONTEXT:"
        echo ${{ toJson(github) }}
        echo "PR Number: ${{ github.event.pull_request.number }}"
        echo "Channel ID: pr-${{ github.event.pull_request.number }}"

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIJAR_7822A }}"
        projectId: tijar-7822a
        channelId: pr-${{ github.event.pull_request.number }}
        expires: 7d
